#!/usr/bin/env bash
# setup.sh — Idempotent workspace setup for game/.
#
# Handles the two things Bazel does NOT manage automatically:
#   1. npm dependencies in node_modules/
#   2. Playwright browser binaries (~/$HOME/Library/Caches/ms-playwright/ on macOS)
#
# Bazel manages its own toolchains (TypeScript, Rust, wasm-bindgen) via bzlmod.
# You do not need rustup, wasm-pack, or a system TypeScript install.
#
# Package manager: npm (ships with node; no pnpm or other global tool required).
#   Lockfile: package-lock.json (generated by npm).
#   node_modules/.bin/playwright is used directly — never pnpm exec.
#
# e2e_test.sh also uses node_modules/.bin/playwright directly (not pnpm exec).
#
# Prerequisites (not installed by this script — must already be on PATH):
#   node    >= 18
#   npm     (ships with node — version >= 9 recommended)
#   python3 (any recent version — used by e2e_test.sh's http.server)
#   bazel   (bazelisk wired as bazel)
#
# Usage:
#   ./setup.sh          # from any directory
#   bash game/setup.sh  # from repo root

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
cd "${SCRIPT_DIR}"

# ── Colour helpers ────────────────────────────────────────────────────────────
green()  { if [[ -t 1 ]]; then printf '\033[0;32m%s\033[0m\n' "$*"; else printf '%s\n' "$*"; fi; }
yellow() { if [[ -t 1 ]]; then printf '\033[0;33m%s\033[0m\n' "$*"; else printf '%s\n' "$*"; fi; }
red()    { if [[ -t 1 ]]; then printf '\033[0;31m%s\033[0m\n' "$*"; else printf '%s\n' "$*"; fi; }

# ── Prerequisite checks ───────────────────────────────────────────────────────
# These are system-level tools the script cannot install.  Fail fast with an
# actionable message rather than a cryptic error mid-run.

MISSING=()

if ! command -v node >/dev/null 2>&1; then
  MISSING+=("node (>= 18) — install via nvm, Homebrew, or system package manager")
fi
if ! command -v npm >/dev/null 2>&1; then
  MISSING+=("npm — ships with node; should be available if node is installed")
fi
if ! command -v python3 >/dev/null 2>&1; then
  MISSING+=("python3 — required by the e2e test HTTP server")
fi
if ! command -v bazel >/dev/null 2>&1; then
  MISSING+=("bazel — install via bazelisk: 'brew install bazelisk' then wire as bazel on PATH")
fi

if [[ ${#MISSING[@]} -gt 0 ]]; then
  red "setup.sh: missing prerequisites:"
  for item in "${MISSING[@]}"; do
    red "  - ${item}"
  done
  exit 1
fi

# ── Step 1: npm dependencies ──────────────────────────────────────────────────
# npm ci is idempotent when package-lock.json is present and up to date.
# It installs exactly what the lockfile specifies (no version drift).
#
# Note: the project previously used pnpm (pnpm-lock.yaml); it was switched to
# npm because pnpm is not reliably available on all machines/CI agents. If
# pnpm-lock.yaml is present it is ignored — package-lock.json is canonical.

yellow "==> npm ci"
npm ci
green "    node_modules up to date"

# ── Step 2: Playwright browser ────────────────────────────────────────────────
# playwright.config.ts uses Playwright's managed Chromium (no channel: override).
# Download it once per machine into ~/Library/Caches/ms-playwright (macOS) or
# ~/.cache/ms-playwright (Linux).  Idempotent — skips download if already current.

yellow "==> playwright install chromium"
node_modules/.bin/playwright install chromium
green "    Playwright Chromium ready"

# ── Done ──────────────────────────────────────────────────────────────────────
green ""
green "Setup complete. To build and test:"
green "  bazel build //..."
green "  bazel test //..."
green ""
green "To serve the app locally:"
green "  ./serve.sh"
